steps:
  - name: docker
    args: ['build', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'kms'
      - 'decrypt'
      -  '--plaintext-file=./.env.yaml'
      - '--ciphertext-file=./.env.yaml.enc'
      - '--keyring=sops'
      - '--key=sops-key'
      - '--location=global'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - GetBuildMessage
      - '--runtime'
      - 'go113'
      - '--trigger-http'
      - '--env-vars-file'
      - '.env.yaml'